package com.securenet.auditor.ui.navigation

sealed class Screen(val route: String) {
    object Dashboard : Screen("dashboard")
    object Scanner : Screen("scanner")
    object Osint : Screen("osint")
    object Vault : Screen("vault")
    object Ping : Screen("ping")
    object SpeedTest : Screen("speed_test")
    object Monitor : Screen("monitor")
    object VulnerabilityReport : Screen("vuln_report")
    object RogueAp : Screen("rogue_ap")
    object WifiScanner : Screen("wifi_scanner")
    object HashTool : Screen("hash_tool")
    object QrScanner : Screen("qr_scanner")
    object Analytics : Screen("analytics")
    object GeoLocation : Screen("geolocation")
    object SnmpInspector : Screen("snmp_inspector")
    object PasswordAuditor : Screen("password_auditor")
    object PasswordManager : Screen("password_manager")
    object SubnetCalculator : Screen("subnet_calculator")
    object Wol : Screen("wol")
    object Bandwidth : Screen("bandwidth")
    object SslScanner : Screen("ssl_scanner")
    object HeaderGrader : Screen("header_grader")
    object SubdomainEnum : Screen("subdomain_enum")
    object PacketAnalyzer : Screen("packet_analyzer")
}
